### ISSUE TITLE
Failed to make on Windows platform

### ISSUE THREAD

**Issue by liaohuanxuan** [LumiOwO/RT-Octree#1]
Thank you for your work!
I make error after successful build.
When I run `make`:`make: *** No targets specified and no makefile found.  Stop.`
I was wondering if this would work on Windows?

**Comment by LumiOwO** [comment]
Yes, it can work on Windows. 
After running the `cmake` command, you can find a `.sln` file in the `build` directory. Just ignore the `make` command and use Visual Studio to build the project. 
We have tested this on Windows 11 with Visual Studio 2019.

**Comment by liaohuanxuan** [comment]
> Yes, it can work on Windows. After running the `cmake` command, you can find a `.sln` file in the `build` directory. Just ignore the `make` command and use Visual Studio to build the project. We have tested this on Windows 11 with Visual Studio 2019.
Thanks for the reply!
I've used VS2019 and VS2022 but it gives me some error during build.
I have tested on Windos 10. 
![image](https://github.com/LumiOwO/RT-Octree/assets/81130410/68b7e803-384a-49a8-80ee-ea3c0b44e681)

**Comment by liaohuanxuan** [comment]
> Yes, it can work on Windows. After running the `cmake` command, you can find a `.sln` file in the `build` directory. Just ignore the `make` command and use Visual Studio to build the project. We have tested this on Windows 11 with Visual Studio 2019.

Thanks for the reply!
I've used VS2019 and VS2022 but it gives me some error during build.
I have tested on Windows 10.

Debug

![image](https://github.com/LumiOwO/RT-Octree/assets/81130410/9ba4a1cc-6933-4f1f-a982-9a2b74e9c247)

Release

> 1>E:\Paper\NERF\prj\RT-Octree\libtorch\include\c10/macros/Macros.h(346): error : redeclaration cannot add dllexport/dllimport to "_wassert"

> 1 error detected in the compilation of "E:/Paper/NERF/prj/RT-Octree/denoiser/extension/filtering.cu".
> 1>filtering.cu
> 1>D:\VS2019\community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.7.targets(790,9): error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe"  --use-local-env -ccbin "D:\VS2019\community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Paper\NERF\prj\RT-Octree\renderer\build\3rdparty\zlib" -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty" -ID:\ANACONDA\Library\include -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty\cnpy" -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty\glew\include" -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty\glm" -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty\misc" -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty\glfw\include" -I"E:\Paper\NERF\prj\RT-Octree\renderer\include" -I"E:\Paper\NERF\prj\RT-Octree\renderer\build\include" -I"E:\Paper\NERF\prj\RT-Octree\renderer\..\denoiser\extension" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -I"E:\Paper\NERF\prj\RT-Octree\libtorch\include" -I"E:\Paper\NERF\prj\RT-Octree\libtorch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include"     --keep-dir x64\Release  -maxrregcount=0  --machine 64 --compile -cudart static -Xcudafe "--display_error_number --diag_suppress=3057 --diag_suppress=3058 --diag_suppress=3059 --diag_suppress=3060" -lineinfo -gencode arch=compute_86,code=sm_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --Werror cross-execution-space-call --no-host-device-move-forward --expt-relaxed-constexpr --expt-extended-lambda -std=c++17 -Xcompiler="/EHsc -Ob2" -g  -D_WINDOWS -DONNX_NAMESPACE=onnx_c2 -DNDEBUG -DGLEW_STATIC -DTINYEXR_USE_MINIZ=0 -DNOMINMAX -D_USE_MATH_DEFINES -DUSE_DISTRIBUTED -DUSE_C10D_GLOO -D"CMAKE_INTDIR=\"Release\"" -D_MBCS -DWIN32 -D_WINDOWS -DNDEBUG_INIT -DNOMINMAX -DGLEW_STATIC -DTINYEXR_USE_MINIZ=0 -D_USE_MATH_DEFINES -DUSE_DISTRIBUTED -DUSE_C10D_GLOO -D"CMAKE_INTDIR=\"Release\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Paper\NERF\prj\RT-Octree\renderer\build\Release\libvolrend_denoiser.pdb /FS   /MT /GR" -o volrend_denoiser.dir\Release\filtering.obj "E:\Paper\NERF\prj\RT-Octree\denoiser\extension\filtering.cu"”

> 2>D:\VS2019\community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.7.targets(879,9): error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe" -dlink -o volrend.dir\Release\libvolrend.device-link.obj -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Paper\NERF\prj\RT-Octree\renderer\build\Release\libvolrend.pdb   /MT /GR" -L"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin/crt" -L"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64" D:\ANACONDA\Library\lib\z.lib D:\ANACONDA\Library\lib\libpng.lib opengl32.lib 3rdparty\glfw\src\Release\glfw3.lib Release\libvolrend_denoiser.lib "C:\Program Files\NVIDIA Corporation\NvToolsExt\lib\x64\nvToolsExt64_1.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64\cufft.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64\curand.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64\cublas.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64\cudnn.lib" "E:\Paper\NERF\prj\RT-Octree\libtorch\lib\c10.lib" "E:\Paper\NERF\prj\RT-Octree\libtorch\lib\kineto.lib" "C:\Program Files\NVIDIA Corporation\NvToolsExt\\lib\x64\nvToolsExt64_1.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64\cudart_static.lib" "E:\Paper\NERF\prj\RT-Octree\libtorch\lib\caffe2_nvrtc.lib" "E:\Paper\NERF\prj\RT-Octree\libtorch\lib\c10_cuda.lib" cudadevrt.lib cudart_static.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib cudart.lib -forward-unknown-to-host-compiler -Wno-deprecated-gpu-targets -D_WINDOWS -Xcompiler=" /GR /EHsc"  -g -Xcudafe "--display_error_number --diag_suppress=3057 --diag_suppress=3058 --diag_suppress=3059 --diag_suppress=3060" -lineinfo -DONNX_NAMESPACE=onnx_c2 -gencode arch=compute_86,code=sm_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --Werror cross-execution-space-call --no-host-device-move-forward --expt-relaxed-constexpr --expt-extended-lambda -Xcompiler="-O2 -Ob2" -DNDEBUG -Xcompiler /MD -Xcompiler=-MD   --machine 64 volrend.dir\Release\common.obj volrend.dir\Release\/src/cuda/n3tree.cu.obj volrend.dir\Release\volrend.obj”已退出，返回代码为 1。

> 3>LINK : fatal error LNK1181: 无法打开输入文件“Release\libvolrend.lib”

**Comment by LumiOwO** [comment]
That's weird. It seems the compile argument is not set correctly... I will fix this out later.

Temp fix: set `/MD` to `/MT` for \***each**\* project in the solution.
`Properties -> Configuration Properties  -> C/C++ -> Code Generation -> Runtime Library -> /MT`
For debugging, please use `RelWithDebInfo` mode instead of `Debug` mode. And notice that if you change the mode from `Release` to `RelWithDebInfo` or vice versa, you need to fix the `/MT` argument again.
![Snipaste_2024-01-05_11-20-34](https://github.com/LumiOwO/RT-Octree/assets/48267313/92c65dd2-6490-426b-80ab-019658cdf236)

**Comment by liaohuanxuan** [comment]
I've set `/MD` to `/MT `for each project in the solution.
Now, both `RelWithDebInfo `and `Release `have same `4` error.

> 1>E:\Paper\NERF\prj\RT-Octree\libtorch\include\c10/macros/Macros.h(346): error : redeclaration cannot add dllexport/dllimport to "_wassert"

>1 error detected in the compilation of "E:/Paper/NERF/prj/RT-Octree/denoiser/extension/filtering.cu".
1>filtering.cu 
1>D:\VS2019\community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.7.targets(790,9): error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe"  --use-local-env -ccbin "D:\VS2019\community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"E:\Paper\NERF\prj\RT-Octree\renderer\build\3rdparty\zlib" -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty" -ID:\ANACONDA\Library\include -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty\cnpy" -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty\glew\include" -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty\glm" -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty\misc" -I"E:\Paper\NERF\prj\RT-Octree\renderer\3rdparty\glfw\include" -I"E:\Paper\NERF\prj\RT-Octree\renderer\include" -I"E:\Paper\NERF\prj\RT-Octree\renderer\build\include" -I"E:\Paper\NERF\prj\RT-Octree\renderer\..\denoiser\extension" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -I"E:\Paper\NERF\prj\RT-Octree\libtorch\include" -I"E:\Paper\NERF\prj\RT-Octree\libtorch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include"     --keep-dir x64\Release  -maxrregcount=0  --machine 64 --compile -cudart static -Xcudafe "--display_error_number --diag_suppress=3057 --diag_suppress=3058 --diag_suppress=3059 --diag_suppress=3060" -lineinfo -gencode arch=compute_86,code=sm_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --Werror cross-execution-space-call --no-host-device-move-forward --expt-relaxed-constexpr --expt-extended-lambda -std=c++17 -Xcompiler="/EHsc -Ob2" -g  -D_WINDOWS -DONNX_NAMESPACE=onnx_c2 -DNDEBUG -DGLEW_STATIC -DTINYEXR_USE_MINIZ=0 -DNOMINMAX -D_USE_MATH_DEFINES -DUSE_DISTRIBUTED -DUSE_C10D_GLOO -D"CMAKE_INTDIR=\"Release\"" -D_MBCS -DWIN32 -D_WINDOWS -DNDEBUG_INIT -DNOMINMAX -DGLEW_STATIC -DTINYEXR_USE_MINIZ=0 -D_USE_MATH_DEFINES -DUSE_DISTRIBUTED -DUSE_C10D_GLOO -D"CMAKE_INTDIR=\"Release\"" -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Paper\NERF\prj\RT-Octree\renderer\build\Release\libvolrend_denoiser.pdb /FS   /MT /GR" -o volrend_denoiser.dir\Release\filtering.obj "E:\Paper\NERF\prj\RT-Octree\denoiser\extension\filtering.cu"”已退出，返回代码为 1。

> 2>D:\VS2019\community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.7.targets(879,9): error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe" -dlink -o volrend.dir\Release\libvolrend.device-link.obj -Xcompiler "/EHsc /W1 /nologo /O2 /FdE:\Paper\NERF\prj\RT-Octree\renderer\build\Release\libvolrend.pdb   /MT /GR" -L"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin/crt" -L"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64" D:\ANACONDA\Library\lib\z.lib D:\ANACONDA\Library\lib\libpng.lib opengl32.lib 3rdparty\glfw\src\Release\glfw3.lib Release\libvolrend_denoiser.lib "C:\Program Files\NVIDIA Corporation\NvToolsExt\lib\x64\nvToolsExt64_1.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64\cufft.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64\curand.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64\cublas.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64\cudnn.lib" "E:\Paper\NERF\prj\RT-Octree\libtorch\lib\c10.lib" "E:\Paper\NERF\prj\RT-Octree\libtorch\lib\kineto.lib" "C:\Program Files\NVIDIA Corporation\NvToolsExt\\lib\x64\nvToolsExt64_1.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64\cudart_static.lib" "E:\Paper\NERF\prj\RT-Octree\libtorch\lib\caffe2_nvrtc.lib" "E:\Paper\NERF\prj\RT-Octree\libtorch\lib\c10_cuda.lib" cudadevrt.lib cudart_static.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib cudart.lib -forward-unknown-to-host-compiler -Wno-deprecated-gpu-targets -D_WINDOWS -Xcompiler=" /GR /EHsc"  -g -Xcudafe "--display_error_number --diag_suppress=3057 --diag_suppress=3058 --diag_suppress=3059 --diag_suppress=3060" -lineinfo -DONNX_NAMESPACE=onnx_c2 -gencode arch=compute_86,code=sm_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --Werror cross-execution-space-call --no-host-device-move-forward --expt-relaxed-constexpr --expt-extended-lambda -Xcompiler="-O2 -Ob2" -DNDEBUG -Xcompiler /MD -Xcompiler=-MD   --machine 64 volrend.dir\Release\common.obj volrend.dir\Release\/src/cuda/n3tree.cu.obj volrend.dir\Release\volrend.obj”已退出，返回代码为 1。

> 3>LINK : fatal error LNK1181: 无法打开输入文件“Release\libvolrend.lib”

![image](https://github.com/LumiOwO/RT-Octree/assets/81130410/86dc8eec-dbd6-4d47-89ad-22e5e300aa2a)

**Comment by LumiOwO** [comment]
I cannot reproduce the error...

> 1>E:\Paper\NERF\prj\RT-Octree\libtorch\include\c10/macros/Macros.h(346): error : redeclaration cannot add dllexport/dllimport to "_wassert"

It appears to be an error from libtorch. You can try checking the version and compile settings of libtorch to resolve the issue.

**Comment by liaohuanxuan** [comment]
> I cannot reproduce the error...
> 
> > 1>E:\Paper\NERF\prj\RT-Octree\libtorch\include\c10/macros/Macros.h(346): error : redeclaration cannot add dllexport/dllimport to "_wassert"
> 
> It appears to be an error from libtorch. You can try checking the version and compile settings of libtorch to resolve the issue.

Thanks for the advice. What version of CUDA do you have on Windows? My CUDA is 11.7, I think my version might be too high.

**Comment by LumiOwO** [comment]
My CUDA version on Windows is 11.6, and my cuDNN version is v8.7.0
